hazelcast:
  network:
    rest-api:
      enabled: true
      endpoint-groups:
        CLUSTER_READ:
          enabled: true
        DATA:
          enabled: true
        HEALTH_CHECK:
          enabled: true
bucket4j:
  enabled: true